/** Opciones de comodidades para el editor de anfitrión (subset tipo Airbnb). */
export const AMENITY_OPTIONS: string[] = [
  "Internet Inalámbrico",
  "Aire Acondicionado",
  "Calefacción",
  "Agua caliente",
  "Cocina",
  "Refrigerador",
  "Microondas",
  "Lavadora",
  "Secadora",
  "Televisión",
  "Estacionamiento Gratuito",
  "Terraza o balcón",
  "Jardín / Patio",
  "Piscina",
  "Detector de humo",
  "Botiquín",
  "Ropa de cama",
  "Amigable Familias/Niños",
  "Permiten Mascotas",
  "Desayuno incluido",
  "Chimenea Interior",
  "Mesa de comedor",
  "Cafetera",
  "Secadora de pelo",
  "Shampoo",
  "Elementos básicos",
];
